// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommitTemplateExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCommitTemplateExtensionPackageString = "859335fa-56fc-4eab-a20e-391f5cdefa3a";
        public static Guid guidCommitTemplateExtensionPackage = new Guid(guidCommitTemplateExtensionPackageString);

        public const string guidCommitTemplateExtensionPackageCmdSetString = "06b29025-59d4-4202-806c-101d0e7b4cb9";
        public static Guid guidCommitTemplateExtensionPackageCmdSet = new Guid(guidCommitTemplateExtensionPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CommitTemplateToolWindowCommandId = 0x0100;
    }
}